title: "望朝门"
email: "181007265@qq.com"
description: "记录学习，展示工作，承接外包，保质保量。"
baseurl: ""
url: "https://www.wangzhaomin.com"
github_username: "qinyuanchunxue"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

#专题功能
#自定义合集目录名称不能以下划线“_”开头。
#当启用时，需要将“_post目录（这也是合集：默认的文章合集）”也移到该目录下。
collections_dir: docs
collections:
  portfolio: #作品集
    collection: "作品集"
    output: true
    permalink: /docs/:collection/:title.html
  jekyll: # 这是新专题的名称，它会和类别产生路径冲突，所以不要重名。
    collection: "Jekyll 学习笔记"
    output: true  # 是否允许集合内文档作为单个文件进行输出
    permalink: /docs/:collection/:title.html # 设置url格式，参考：http://jekyllcn.com/docs/permalinks/
  web: #web前端开发
    collection: "Web 学习笔记"
    output: true
    permalink: /docs/:collection/:title.html
  wordpress: #wordpress相关
    collection: "WordPress 学习笔记"
    output: true
    permalink: /docs/:collection/:title.html
  posts: #笔记
    collection: "笔记"
    output: true
    permalink: /docs/:collection/:title.html
  manuals: #手册，用于创建用户手册，或者未来可能用到的手册
    collection: "使用手册"
    output: true
    permalink: /docs/:collection/:title.html
  favorite: #收藏夹，用于收藏网址和其他网站的文章
    collection: "收藏夹"
    output: true
    permalink: /docs/:collection/:title.html



#给不同专题设置相应的默认布局。
#参考文档1：https://jekyllrb.com/docs/configuration/front-matter-defaults/
#参考文档2：https://www.typeerror.org/docs/jekyll~4/configuration/front-matter-defaults/index
defaults:
  -
    scope:
      path: ""
      type: "portfolio" # a collection in your site, in plural form
    values:
      layout: "single-product"
  -
    scope:
      path: ""
      type: "jekyll"
    values:
      layout: "single-post"
  -
    scope:
      path: ""
      type: "web"
    values:
      layout: "single-post"
  -
    scope:
      path: ""
      type: "wordpress"
    values:
      layout: "single-post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "single-post"
  -
    scope:
      path: ""
      type: "manuals"
    values:
      layout: "single-post"
  -
    scope:
      path: ""
      type: "favorite"
    values:
      layout: "single-post"