# Welcome to Jekyll!
#
#此配置文件用于影响整个博客的设置值
#你需要设置一次，之后很少再编辑。如果你发现
#如果您经常编辑此文件，请考虑使用Jekyll的数据文件
#需要经常更新的数据的特性。
#
#由于技术原因，使用时不会自动重新加载此文件
#'bundle exec jekyll serve'。如果更改此文件，请重新启动服务器进程。
#
# 如果您需要有关YAML语法的帮助，以下是一些快速参考资料：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
#站点设置
#这些是用来个性化你的新网站。如果你查看HTML文件，
#您将看到它们通过{{site.title}}, {{ site.email }}，以此类推。
#您可以创建任何您想要的自定义变量，并且可以访问它们
#在模板中通过{{ site.*** }}.

title: 望朝门
email: hetieliancheng@outlook.com
description: >- # 这意味着在“baseurl:”之前忽略换行符：
  人对了，世界就对了。
baseurl: "" # 站点的子路径，例如/blog
url: "" # 站点的基本主机名和协议，例如：http://example.com

# 生成设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# 分页代码
paginate: 12

# 集合
collections:
  jekyll: # 这是专题名称
    output: true  # 允许渲染输出
    permalink: /jekyll/:path/ # 设置文章路径

# 默认设置，文章类型不同，使用的模板也不同
defaults:
  - scope:
      path: ""
      type: "jekyll"
    values:
      layout: "jekyll"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"